// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNON9eUJQzkPdbhE4wRGuyKm4o-m56bZk',
    appId: '1:912907954011:web:2c087e64c5d7c577bb1c7e',
    messagingSenderId: '912907954011',
    projectId: 'chat-app-412d9',
    authDomain: 'chat-app-412d9.firebaseapp.com',
    storageBucket: 'chat-app-412d9.appspot.com',
    measurementId: 'G-VYD7PGY53S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMrWNCwvYVXnju4qWVRIMWWjkuXHeIMM',
    appId: '1:912907954011:android:e3ccd5d58c48e9debb1c7e',
    messagingSenderId: '912907954011',
    projectId: 'chat-app-412d9',
    storageBucket: 'chat-app-412d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAbGxIH68lJjg9jNlaSZ5jYCPyAOBxW4E',
    appId: '1:912907954011:ios:80cd981f00082672bb1c7e',
    messagingSenderId: '912907954011',
    projectId: 'chat-app-412d9',
    storageBucket: 'chat-app-412d9.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
